# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97173dc162395676ef7254c307de803d1e74cdcdb86470dbb251a040336c3758dbe4c53217b7af0fd07c9dfe1c474067c1883c423e5245ca5657dc3f3f16055f

test:
  secret_key_base: 332eb3934ff44b53593f928d9d0dace1c48dab6c8ea81f0958937ec7125318a8b5355a80f01219354981b6f9286040b8b8af77084f1cb5f231f17ab99fd24396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
